import Image from 'next/image'
import Header from '../components/header/header';
import BreadCrumbs from '@/components/breadcrumbs/breadcrumbs';
import Table from '@/components/table/table';

export const metadata = {
  title: 'Editais e Licitações - Prefeitura do Município de Francisco Morato',
  description: 'Generated by create next app',
}


export default function Home() {
  return (
    <>
      <Header />
      <Table />
      {/* <BreadCrumbs /> */}
      {/* <hr className='mt-3 ms-5'></hr> */}
    </>
  )
}
